config/routes.rb
Rails.application.routes.draw do

 	resources :comments, only: [:edit, :create, :update, :destroy]

	resources :blog_posts

	root 'blog_posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

	has_many :comments, dependent: :destory

	validates :title, :blog_entry, presence: true
	validates :title, uniqueness: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :blog_post

	validates :comment_entry, :blog_post_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

before_action :set_blog_post, only: [:show, :edit, :update, :destory]
  def index
  	@blog_posts = BlogPost.all
  end

  def show
  	@comment = Comment.new
  end

  def new
  	@blog_posts = BlogPost.all
  end

  def edit
  end

  def create
  	@blog_posts = BlogPost.new(blog_post_params)

  	respond_to do |form|
  		if @blog_post.save
  			format.html { redirect_to blog_post_path(id: @blog_post.id), notice: "Blog Post was created successfully!"}
  		else
  			format.html { render :new }
  		end
  	end
  end

  def update
  	
  	respond_to do |format| 
  		if @blog_post.update(blog_post_params)
  			format.html { redirect_to blog_post_path(id: @blog_post.id), notice: "Blog post was updated successfully!"}
  		else 
  			format.html { render :edit }
  		end
  	end
  end

  def destroy
  	

  	@blog_post.destroy

  	respond_to do |format|
  		format.html { redirect_to blog_posts_path, notice: "your blog post was destoryed"}
  end
 end


  private 

  def blog_post_params 
  	params.require(:blog_post).permit(:title, :blog_entry, :author)
  end

  def blog_post_params
  	params.require(:blog_post).permit(:title, :blog_entry, :author)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_comment, only: [:edit, :update, :destory]
  def edit
  end

 def create
 	@comment = Comment.new(comment_params)

 	respond_to do |format|
 		if @comment.save
 			format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was created successfully!!" }
 		else 
 			format.html { redirect_back(fallback_location: root_path, notice: "Comment failed to Post!")}
		end
	end
end

def update
	respond_to do |format|
		if @comment.update(comment_params)
			format.html{ redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was updated successfully"}
		else 
			format.html { render :edit }
		end
	end
end

def destroy
	respond_to do |format|
		format.html { redirect_to blog_post_path,(id: @comment.blog_post_id), notice: "Your comment was destoryed"}
	end
end

private

	def comment_params
		params.require(:comment).permeit(:author, :comment_entry, :blog_post_path)
	end

	def set_comment 
		@comment = Comment.find(params[:id])
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>
    <% if @blog_post.errors.any? %>
        <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this Blog Post from being saved: </h2>
        <ul>
          <% @blog_post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

    <div class="form-group">
        <%= form.text_field :title, class: "form-control", placeholder: "Blog Title..." %>
    </div>

    <div class="form-group">
        <%= form.text_field :author, class: "form-control", placeholder: "Your name here..." %>
    </div>

    <div class="form-group">
        <%= form.text_area :blog_entry, class: "form-control", rows: 12, placeholder: "Tell us something..."%>
    </div>
    
    <div class="actions">
        <%= form.submit "Post", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1> Editing Blog Post </h1>

<%= form_with(model: @blog_post, local: true) do |form| %>
	<% if @blog_post.errors.any? %>
		<h2><%= pluralize(@blog_post.errors.count, "error" %> prohibited this Blog Post from being saved: 
		</h2>
		<ul>
			<% @blog_post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<div class="form-grouping">
		<%= form.text_field :title, class: "form-control", placeholder: "Blog Title. . . " %>
	</div>
	<div class="form-group">
		<%= form.text_area :blog_entry, class: "form-control", rows: 12, placeholder: "tell us something. . ."%>
	</div>
	<div class="actions">
		<%= form.submit "Post", class "btn btn-primary" %>
	</div>

<% end %>

<br>
<%= link_to "back", blog_post_path(id: @blog_post.id), class: "btn btn-info" %>
<%= link_to "all blog posts", blog_post_path, class: "btn btn-default" %>

app/views/blog_posts/index.html.erb
<h1>Current Blog Posts</h1>

	<% @blog_posts.each do |blog_post| %>

		<div calss="panel panel-default">
			<div class="panel=-heading">
				<%= blog_post.title %>
			</div>
			<div class="panel-body">
				by <%= blog_post.author %><br>
				<p><%= blog_post.created_at.strftime('%m/%d/%Y at %I:%M%p') %></p>
				<p><%= blog_post.blog_entry %></p>
			</div>
			<div class="panel-footer">
				<%= link_to "Show", blog_post_path(id: blog_post.id), class: "btn btn-info" %>
				<%= link_to "Edit", edit_blog_post_path(id: blog_post.id), class: "btn btn-warning" %>
				<%= link_to "Destroy", blog_post_path(id: blog_post.id), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-danger" %>
			</div>
		</div>
	<% end %>

<% link_to "New Blog Post", new_blog_post_path, class: "btn btn-success" %>

app/views/blog_posts/new.html.erb
<h1>Create a New Blog Post</h1>

<%= render 'form' %>

<%= link_to "all blog posts", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<%= @blog_post.title %>
	</div>
	<div class="panel-body">
		<p><%= @blog_post.author %></p>
		<p><%= time_ago_in_words (@blog_post.created_at) %> ago </p>
		<p><%= @blog_post.blog_entry %></p>
	</div>
	<div class="panel-footer">
		<%= link_to "Edit", edit_blog_post_path(id: @blog_post.id), class: "btn btn-warning" %>
		<%= link_to "all Blog Posts", blog_post_path, class: "btn btn-default" %>
	</div>
</div>

<div class="panel panel-success">
	<div class="panel-heading">
		make a comment. . .
	</div>
	<div class="panel-body">
		<%= render 'comments/form' %>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		All Comments. . .
	</div>
	<div class="panel-body">
		<%= render 'comments/comment' %>
	</div>
</div>

app/views/comments/_comment.html.erb
<% @blog_post.comment.each do |comment| %>
	<h4><%= comment.author %></h4>
	<p><%= time_ago_in_words(comment.created_at) %> ago</p>
	<p><%= comment.coment_entry %></p>

<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>

	<% if @comment.errors.any? %>
        <div class="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "errors") %> prohibited this comment from being saved:</h2>
        </div>
        <ul>
            <% @comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
    <div class="form-group">
        <%= form.text_field :author, class: "form-control", placeholder: "Your name here..." %>
    </div>
    <div class="form-group">
        <%= form.text_area :comment_entry, class: "form-control", rows: 4, placeholder: "Your comment here..." %>
    </div>
    <div class="form-group">
        <%= form.number_field :blog_post_id, value: @blog_post.id %>
    </div>
    <div class="actions">
        <%= form.submit "Set Comment", class: "btn btn-default" %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    <%= yield %>
	</div>
  </body>
</html>